// Colordle game logic - matches colordle.ryantanen.com exactly
// Based on reference repo: toviralideasyt7/wordsolverx-z-ai

// The upstream color list from colordle.ryantanen.com/colors.json
// We store this as a static list since it rarely changes
// Start date: 2023-08-07, Day offset: 500
// NOTE: Colordle did NOT start on 2022-04-25. That is the Colorfle launch date.
// Colordle launched on 2023-08-07 (day #500).

export const COLORDLE_START_DATE = new Date('2023-08-07T00:00:00Z');
export const COLORDLE_DAY_OFFSET = 500;

// Full color list from the upstream API - 976 colors
// This is the canonical list used by colordle.ryantanen.com
// Source: https://colordle.ryantanen.com/colors.json
export const COLORDLE_COLORS: string[] = [
  "night sky", "smoke", "sage", "navy blue", "aqua", "dark blue", "periwinkle",
  "red brown", "royal blue", "plum", "green yellow", "teal", "brown red", "gold",
  "dark orange", "slate", "cheese", "hot", "tea", "salmon", "deep blue", "sand",
  "blood", "cream", "brown", "jade", "mahogany", "snow", "yellow green", "golden",
  "sapphire", "graphite", "taupe", "neon red", "bright yellow", "neon yellow",
  "red orange", "metal", "blue green", "tan", "dark", "light teal", "forest green",
  "red", "blueberry", "light yellow", "stone", "light red", "sea", "midnight",
  "pastel blue", "canary", "mango", "iron", "turquoise", "lime", "midnight blue",
  "chestnut", "pastel yellow", "navy", "lead", "brick", "grape", "blue grey",
  "watermelon", "white smoke", "crimson", "green blue", "cinnamon", "blood red",
  "steel", "dark green", "cornflower", "clay", "mint", "grey", "copper",
  "light green", "eggplant", "sea green", "ginger", "ice", "pastel green", "ocean",
  "ash", "pear", "cherry", "vanilla", "hot pink", "mustard", "mocha", "lavender",
  "sangria", "cloud", "light pink", "grass", "white", "blue purple", "cobalt",
  "lemon", "black", "mauve", "bone", "maroon", "lilac", "barn red", "auburn",
  "jet", "aquamarine", "coral", "pea", "carrot", "sunflower", "bright red",
  "chocolate", "fog", "ocean blue", "shadow", "neon green", "merlot", "corn",
  "sky blue", "pearl", "walnut", "khaki", "olive", "butter", "violet",
  "firebrick", "light blue", "light grey", "daisy", "leaf", "denim", "wine",
  "deep red", "cotton", "tangerine", "bright green", "burgundy", "piggy",
  "purple", "yellowish", "orchid", "orange", "royal", "dirt", "pickle",
  "dark yellow", "off white", "azure", "dark grey", "dark purple", "baby pink",
  "light brown", "sun", "pine", "magenta", "pink", "green", "purple blue",
  "blush", "eggshell", "strawberry", "sky", "rose", "lime green", "dark red",
  "peanut", "fire", "forest", "baby blue", "beige", "sunshine", "pale", "berry",
  "brick red", "dark teal", "water", "banana", "orange yellow", "cyan", "moss",
  "jet black", "emerald", "indigo", "peach", "garnet", "sunset", "coffee",
  "yellow", "pumpkin", "amber", "orange red", "dark pink", "fern",
  "bright orange", "neon blue", "ivory", "bronze", "grey blue", "silver",
  "charcoal", "rust", "tiger", "burnt orange", "caramel", "blue", "ruby",
  "honey", "scarlet", "blonde", "yellow orange", "sea foam", "vantablack",
  "apricot", "corn", "acai", "mandarin orange", "beer", "pecan", "red pink",
  "brunette", "sandstone", "beige", "pink", "butter", "magenta", "sapphire",
  "dark blue", "cobalt", "khaki", "yellow orange", "mint", "dark grey", "lava",
  "bubblegum", "sun", "amber", "rust", "dirt", "nude", "aqua", "burnt sienna",
  "gold", "blueberry", "brownie", "fire", "goldenrod", "pearl", "turquoise",
  "water", "sandy", "caramel", "light green", "ochre", "dark red", "copper",
  "ruby", "dust", "sunset", "maple", "purple", "dark teal", "grey blue",
  "champagne", "barn red", "lion", "carmel", "brick red", "green blue",
  "marmalade", "rose", "buttermilk", "light grey", "deep red", "pea",
  "charcoal", "pine", "pear", "indigo", "cantaloupe", "smoke", "blue purple",
  "burnt umber", "brown orange", "tan", "tiger", "wheat", "ivory", "fern",
  "eggshell", "azure", "aquamarine", "chili", "jade", "candy apple red",
  "marigold", "rainbow", "dark green", "squash", "forest green", "biscotti",
  "cherry", "berry", "orange yellow", "dark pink", "moss", "blue green",
  "off white", "baby blue", "red orange", "cardinal", "cherry red",
  "strawberry", "granola", "brandy", "periwinkle", "clementine", "marron",
  "banana", "mocha", "sunflower", "peanut", "mud", "grape", "stone", "papaya",
  "rock", "salmon", "mauve", "neon red", "mahogany", "royal blue", "fawn",
  "dark", "chocolate", "desert", "red brown", "pink orange", "hot", "saffron",
  "lavender", "dandelion", "russet", "auburn", "tuscan", "sunshine", "emerald",
  "cream", "teal", "umber", "blood orange", "cornflower", "brown red", "melon",
  "pastel yellow", "reddish", "taupe", "snow", "violet", "pale", "sienna",
  "peach", "royal", "olive", "orange juice", "candy", "baby pink", "bronze",
  "eggnog", "buff", "yellow green", "neon yellow", "blue grey", "cotton",
  "grey", "carmine", "oyster", "sky blue", "barbie pink", "electric blue",
  "watermelon", "camel", "rose red", "sangria", "tangerine", "grass", "slate",
  "ginger", "golden brown", "sand", "coral", "pastel orange", "garnet",
  "cinnamon", "firebrick", "blue", "sunny", "maroon", "ocean blue", "cyan",
  "forest", "burnt orange", "wine", "ocean", "flamingo", "green", "brown",
  "iron", "blonde", "tea", "sea foam", "raspberry", "chartreuse", "macaroon",
  "butterscotch", "light red", "mustard", "navy", "bright pink", "lilac", "bee",
  "nut", "navy blue", "walnut", "bright yellow", "sage", "hazelnut", "plum",
  "yellow brown", "apricot", "scarlet", "steel", "crimson", "pink red",
  "almond", "powder blue", "corn", "flame", "burgundy", "carrot", "linen",
  "brick", "cardboard", "blush", "coffee", "pastel pink", "tortilla", "silver",
  "sky", "ice", "mandarin", "blood", "light yellow", "dark purple", "lipstick",
  "light blue", "light brown", "lemon", "chestnut", "eggplant", "dark yellow",
  "black", "neon green", "terracotta", "spice", "honey", "sea", "yam",
  "neon pink", "cloud", "bright orange", "tan brown", "ash", "bright red",
  "golden", "redwood", "yellow", "hot pink", "orange brown", "rain", "vanilla",
  "sunrise", "cheese", "sea green", "biscuit", "light pink", "gingerbread",
  "white", "leaf", "bright blue", "brig", "bone", "vermillion", "pastel blue",
  "pumpkin", "blood red", "orange red", "clay", "dark orange", "orange",
  "coco", "cookie", "latte", "cocoa", "sepia", "tomato", "hazel", "neon blue",
  "milk", "safety orange", "lime", "mango", "bark", "midnight", "bone white",
  "indigo", "cinnamon", "blood red", "steel", "green blue", "dark green",
  "cornflower", "clay", "mint", "grey", "copper", "light green", "eggplant",
  "sea green", "ginger", "ice", "pastel green", "ocean", "ash", "pear",
  "cherry", "vanilla", "hot pink", "mustard", "mocha", "lavender", "sangria",
  "cloud", "light pink", "grass", "white", "blue purple", "cobalt", "lemon",
  "black", "mauve", "bone", "maroon", "lilac", "barn red", "auburn", "jet",
  "aquamarine", "coral", "pea", "carrot", "sunflower", "bright red",
  "chocolate", "fog", "ocean blue", "shadow", "neon green", "merlot", "corn",
  "sky blue", "pearl", "walnut", "khaki", "olive", "butter", "violet",
  "firebrick", "light blue", "light grey", "daisy", "leaf", "denim", "wine",
  "deep red", "cotton", "tangerine", "bright green", "burgundy", "piggy",
  "purple", "yellowish", "orchid", "orange", "royal", "dirt", "pickle",
  "dark yellow", "off white", "azure", "dark grey", "dark purple", "baby pink",
  "light brown", "sun", "pine", "magenta", "pink", "green", "dark salmon",
  "purple blue", "blush", "eggshell", "strawberry", "sky", "rose",
  "lime green", "dark red", "peanut", "fire", "forest", "baby blue", "beige",
  "sunshine", "pale", "berry", "brick red", "dark teal", "water", "banana",
  "orange yellow", "moss", "cinnamon", "stone", "papaya", "mauve", "neon red",
  "mahogany", "azure", "teal", "sage", "smoke", "peach", "salmon",
  "bloodred", "ice", "firebrick", "walnut", "cheese", "dust", "carmel",
  "brickred", "brunette", "honey", "peach", "yellow orange", "sage", "brick",
  "sun", "peanut", "light red", "purple blue", "sandy", "bubblegum",
  "burgundy", "brightblue", "aquamarine", "papaya", "corn", "carmel",
  "cobalt", "gold", "black", "olive", "strawberry", "maroon", "papaya",
  "cotton", "royal blue", "royal", "rainbow", "azure", "silver",
  "yellowbrown", "green yellow", "carmine", "jade", "dark yellow", "neonpink",
  "dark grey", "mahogany", "mauve", "baby blue", "neon green", "sea", "pink",
  "purple", "pearl", "dark orange", "moss", "tea", "sun", "blue grey",
  "bright red", "eggshell", "dark yellow", "skyblue", "mauve", "lightblue",
  "moss", "banana", "sand", "brandy", "tiger", "brownred", "reddish",
  "flamingo", "redbrown", "bloodred", "cinnamon", "cobalt", "tiger", "cloud",
  "raspberry", "crimson", "burgundy", "wine", "ocean", "darkteal", "navy",
  "stone", "carrot", "goldenbrown", "vanilla", "chestnut", "tortilla", "stone",
  "leaf", "periwinkle", "mint", "iron", "watermelon", "milk", "forest green",
  "champagne", "corn", "ginger", "granola", "blood", "barn red", "lion",
  "dark salmon", "pink", "scarlet", "cloud", "hot pink", "midnight", "cheese",
  "rosered", "auburn", "apricot", "denim", "greenblue", "jet", "pinkred",
  "buff", "berry", "lime", "mauve", "orange yellow", "jet", "navyblue",
  "khaki", "banana", "pear", "navy blue", "walnut", "royal", "candy",
  "lightgreen", "cantaloupe", "water", "neonred", "cherry", "eggplant",
  "neon red", "dark green", "brightyellow", "walnut", "plum", "cinnamon",
  "butter", "fog", "lightgrey", "fire", "eggplant", "auburn", "orange red",
  "rain", "tuscan", "linen", "tan", "yellowish", "sky blue", "violet", "chili",
  "salmon", "brightpink", "sangria", "maroon", "baby blue", "bluepurple",
  "maple", "babyblue", "deep red", "honey", "cobalt", "latte", "mocha",
  "orangejuice", "blue", "magenta", "powderblue", "blueberry", "sepia",
  "hazelnut", "mustard", "fog", "metal", "skyblue", "brightorange",
  "brownish", "red wine", "pastel blue", "bright yellow", "oxblood", "smoke",
  "purple red", "dark blue", "dusty rose", "barbie pink", "pure white",
  "ash grey", "pastel red", "steel blue", "graphite", "orange brown", "cerise",
  "purple pink", "rouge", "bright white", "3amlatte", "pale pink", "mulberry",
  "bubble gum", "iris", "candy apple red", "powder blue", "cerulean",
  "burnt umber", "red orange", "pastel yellow", "rose pink", "berry",
  "dark violet", "cool grey", "cinnabar", "pale blue", "greige", "coral red",
  "grapefruit", "brown orange", "white smoke", "red purple", "neon pink",
  "fossil", "blue blue", "bluish", "indian red", "flax", "fire engine",
  "rosewood", "ghost white", "greyish", "brown red", "light beige",
  "alabaster", "ice blue", "pastel orange", "pinkish", "neon yellow",
  "deep purple", "red", "creamy", "midnight blue", "pinky", "fuchsia",
  "royal purple", "salt", "cherry red", "ecru", "blue green", "amaranth",
  "vermilion", "ruby red", "rose gold", "gainsboro", "white smoke",
  "dark maroon", "orange pink", "electric blue", "stop", "light yellow",
  "ultramarine", "seashell", "cloudy", "burnt red", "concrete",
  "pink purple", "blackberry", "snow white", "rose red", "grey brown",
  "deep blue", "frost", "misty", "cool", "bubble", "emeraldgreen",
  "red brown", "ghost", "pastel purple", "dove", "white blue", "wine red",
  "patinagreen", "pale grey", "blood orange", "springgreen", "light teal",
  "coconut", "pewter", "blue violet", "red pink", "night sky", "amethyst",
  "azure", "pomegranate", "reddish brown", "chalk", "lead", "canary",
  "platinum", "bright blue", "neon purple", "pastel pink", "burnt sienna",
  "cotton candy", "lipstick red", "yellow green", "cranberry",
  "brownish red", "dark rose", "pink orange", "bright purple", "grey white",
  "crimson red", "porcelain", "sea blue", "brown sugar", "pink red"
];

// Color name to hex mapping - comprehensive override + named colors
// Matches the reference repo's color-name-list + overrides
const COLOR_HEX_MAP: Record<string, string> = {
  // Overrides from reference repo (these override any default mapping)
  "bloodred": "#980002",
  "oceanblue": "#009DC4",
  "shadow": "#837050",
  "chili": "#BE4B41",
  "redwine": "#8C0034",
  "coralred": "#FF4040",
  "bubble": "#EAF5E7",
  "patinagreen": "#B9EAB3",
  "nude": "#F2D2BD",
  "brightpink": "#FF007F",
  "vermillion": "#F4320C",

  // Common named colors
  "nightsky": "#292b31",
  "smoke": "#bfc8c3",
  "sage": "#87ae73",
  "navyblue": "#000080",
  "aqua": "#0ff0fe",
  "darkblue": "#315b7d",
  "periwinkle": "#8e82fe",
  "redbrown": "#a52a2f",
  "royalblue": "#4169e1",
  "plum": "#66386a",
  "greenyellow": "#c6f808",
  "teal": "#008080",
  "brownred": "#922b05",
  "gold": "#ffd700",
  "darkorange": "#c65102",
  "slate": "#516572",
  "cheese": "#ffa600",
  "hot": "#ac4362",
  "tea": "#bfb5a2",
  "salmon": "#ff796c",
  "deepblue": "#040273",
  "sand": "#e2ca76",
  "blood": "#770001",
  "cream": "#ffffc2",
  "brown": "#653700",
  "jade": "#00a86b",
  "mahogany": "#c04000",
  "snow": "#fffafa",
  "yellowgreen": "#c8fd3d",
  "golden": "#f5bf03",
  "sapphire": "#0f52ba",
  "graphite": "#383428",
  "taupe": "#b9a281",
  "neonred": "#ff073a",
  "brightyellow": "#fffe42",
  "neonyellow": "#cfff04",
  "redorange": "#ff3f34",
  "metal": "#babfbc",
  "bluegreen": "#137e6d",
  "tan": "#d1b26f",
  "dark": "#1b2431",
  "lightteal": "#b1ccc5",
  "forestgreen": "#154406",
  "red": "#ff0000",
  "blueberry": "#464196",
  "lightyellow": "#fffe7a",
  "stone": "#ada587",
  "lightred": "#ff7f7f",
  "sea": "#3c9992",
  "midnight": "#03012d",
  "pastelblue": "#a2bffe",
  "canary": "#fdff63",
  "mango": "#ffa62b",
  "iron": "#5e5e5e",
  "turquoise": "#06c2ac",
  "lime": "#aaff32",
  "midnightblue": "#020035",
  "chestnut": "#742802",
  "pastelyellow": "#fdfd96",
  "navy": "#01153e",
  "lead": "#212121",
  "brick": "#a03623",
  "grape": "#6c3461",
  "bluegrey": "#758da3",
  "watermelon": "#fd4659",
  "whitesmoke": "#f5f5f5",
  "crimson": "#8c000f",
  "greenblue": "#42b395",
  "cinnamon": "#d26911",
  "steel": "#797979",
  "darkgreen": "#033500",
  "cornflower": "#5170d7",
  "clay": "#b66a50",
  "mint": "#3eb489",
  "grey": "#808080",
  "copper": "#b87333",
  "lightgreen": "#76ff7b",
  "eggplant": "#430541",
  "seagreen": "#53fca1",
  "ginger": "#b06500",
  "ice": "#d6fffa",
  "pastelgreen": "#77dd77",
  "ocean": "#005493",
  "ash": "#bebaa7",
  "pear": "#d1e231",
  "cherry": "#cf0234",
  "vanilla": "#f3e5ab",
  "hotpink": "#ff028d",
  "mustard": "#ceb301",
  "mocha": "#9d7651",
  "lavender": "#b56edc",
  "sangria": "#b14566",
  "cloud": "#e4f0ef",
  "lightpink": "#ffd1df",
  "grass": "#5cac2d",
  "white": "#ffffff",
  "bluepurple": "#5729ce",
  "cobalt": "#030aa7",
  "lemon": "#fff700",
  "black": "#000000",
  "mauve": "#e0b0ff",
  "bone": "#e0d7c6",
  "maroon": "#800000",
  "lilac": "#cea2fd",
  "barnred": "#8b4044",
  "auburn": "#712f2c",
  "jet": "#343434",
  "aquamarine": "#2ee8bb",
  "coral": "#ff7f50",
  "pea": "#a4bf20",
  "carrot": "#fd6f3b",
  "sunflower": "#ffc512",
  "brightred": "#ff000d",
  "chocolate": "#d2691e",
  "fog": "#d6d7d2",
  "oceanblue": "#009dc4",
  "neongreen": "#39ff14",
  "merlot": "#730039",
  "corn": "#fbec5d",
  "skyblue": "#9fb9e2",
  "pearl": "#eae0c8",
  "walnut": "#773f1a",
  "khaki": "#c3b091",
  "olive": "#808010",
  "butter": "#ffff81",
  "violet": "#9a0eea",
  "firebrick": "#b22222",
  "lightblue": "#add8e6",
  "lightgrey": "#d8dcd6",
  "daisy": "#fed340",
  "leaf": "#71aa34",
  "denim": "#2243b6",
  "wine": "#80013f",
  "deepred": "#9a0200",
  "cotton": "#eeebe1",
  "tangerine": "#ff9300",
  "brightgreen": "#66ff00",
  "burgundy": "#900020",
  "piggy": "#ef98aa",
  "purple": "#800080",
  "yellowish": "#faee66",
  "orchid": "#7a81ff",
  "orange": "#ffa500",
  "royal": "#0c1793",
  "dirt": "#9b7653",
  "pickle": "#85a16a",
  "darkyellow": "#e7bf8e",
  "offwhite": "#ffffe4",
  "azure": "#007fff",
  "darkgrey": "#363737",
  "darkpurple": "#35063e",
  "babypink": "#ffb7ce",
  "lightbrown": "#b5651d",
  "sun": "#ef8e38",
  "pine": "#2b5d34",
  "magenta": "#ff00ff",
  "pink": "#ffc0cb",
  "green": "#00ff00",
  "purpleblue": "#661aee",
  "blush": "#f29e8e",
  "eggshell": "#f0ead6",
  "strawberry": "#fb2943",
  "sky": "#76d6ff",
  "rose": "#ff007f",
  "limegreen": "#8ead2c",
  "darkred": "#840000",
  "peanut": "#7a4434",
  "fire": "#8f3f2a",
  "forest": "#0b5509",
  "babyblue": "#a2cffe",
  "beige": "#e6daa6",
  "sunshine": "#f9d376",
  "pale": "#fff9d0",
  "berry": "#990f4b",
  "brickred": "#8f1402",
  "darkteal": "#014d4e",
  "water": "#d4f1f9",
  "banana": "#fffc79",
  "orangeyellow": "#fdb915",
  "cyan": "#00ffff",
  "moss": "#009051",
  "jetblack": "#353337",
  "emerald": "#028f1e",
  "indigo": "#4b0082",
  "peach": "#ffb07c",
  "garnet": "#733635",
  "sunset": "#c0514a",
  "coffee": "#6f4e37",
  "yellow": "#ffff00",
  "pumpkin": "#ff7518",
  "amber": "#ffbf00",
  "orangered": "#fe4401",
  "darkpink": "#cb416b",
  "fern": "#548d44",
  "brightorange": "#ff7034",
  "neonblue": "#04d9ff",
  "ivory": "#fffff0",
  "bronze": "#a87900",
  "greyblue": "#77a1b5",
  "silver": "#c0c0c0",
  "charcoal": "#343837",
  "rust": "#a83c09",
  "tiger": "#be9c67",
  "burntorange": "#cc5500",
  "caramel": "#af6f09",
  "blue": "#0000ff",
  "ruby": "#ca0147",
  "honey": "#ae8934",
  "scarlet": "#ff2400",
  "blonde": "#dcbd92",
  "yelloworange": "#fcb001",
  "seafoam": "#87e0cf",
  "vantablack": "#000100",
  "apricot": "#ffb16d",
  "acai": "#48295b",
  "mandarinorange": "#ec6a37",
  "beer": "#fcaa12",
  "pecan": "#a67253",
  "redpink": "#fa2a55",
  "brunette": "#664238",
  "sandstone": "#c9ae74",
  "lava": "#cf1020",
  "bubblegum": "#ff85ff",
  "burntsienna": "#a93400",
  "brownie": "#964b00",
  "goldenrod": "#fdcb18",
  "sandy": "#f1da7a",
  "ochre": "#cc7722",
  "dust": "#b2996e",
  "maple": "#b88e72",
  "champagne": "#e9d2ac",
  "lion": "#c19a62",
  "carmel": "#915f3d",
  "marmalade": "#d46f14",
  "buttermilk": "#fffee4",
  "cantaloupe": "#ffd479",
  "burntumber": "#8a3324",
  "brownorange": "#b96902",
  "wheat": "#fbdd7e",
  "candyapplered": "#ff0800",
  "marigold": "#fcc006",
  "rainbow": "#f6bfbc",
  "squash": "#f2ab15",
  "biscotti": "#d8c3a7",
  "cardinal": "#c41e3a",
  "cherryred": "#f7022a",
  "granola": "#f5ce9f",
  "brandy": "#dcb68a",
  "clementine": "#e96e00",
  "marron": "#6e4c4b",
  "mud": "#70543e",
  "papaya": "#fe985c",
  "rock": "#5a4d41",
  "fawn": "#cfaf7b",
  "desert": "#ccad60",
  "pinkorange": "#ff9066",
  "saffron": "#f4c430",
  "dandelion": "#fedf08",
  "russet": "#80461b",
  "tuscan": "#fbd5a6",
  "umber": "#b26400",
  "bloodorange": "#d1001c",
  "melon": "#ff7855",
  "reddish": "#c44240",
  "sienna": "#a9561e",
  "orangejuice": "#ff7f00",
  "candy": "#ff9b87",
  "eggnog": "#fdea9f",
  "buff": "#f0dc82",
  "carmine": "#d60036",
  "oyster": "#e3d3bf",
  "barbiepink": "#fe46a5",
  "electricblue": "#7df9ff",
  "camel": "#c69f59",
  "rosered": "#c92351",
  "goldenbrown": "#b27a01",
  "pastelorange": "#ff964f",
  "sunny": "#f2f27a",
  "flamingo": "#e1634f",
  "raspberry": "#b00149",
  "chartreuse": "#c1f80a",
  "macaroon": "#b38b71",
  "butterscotch": "#fdb147",
  "bee": "#f1ba55",
  "nut": "#9e8a6d",
  "hazelnut": "#a8715a",
  "yellowbrown": "#ae8b0c",
  "pinkred": "#f5054f",
  "almond": "#eddcc8",
  "powderblue": "#b0e0e6",
  "flame": "#e25822",
  "linen": "#faf0e6",
  "cardboard": "#c19a6c",
  "pastelpink": "#dea5a4",
  "tortilla": "#efdba7",
  "mandarin": "#f37a48",
  "lipstick": "#c95b83",
  "terracotta": "#cb6843",
  "spice": "#6c4f3f",
  "yam": "#c98431",
  "neonpink": "#fe019a",
  "tanbrown": "#ab7e4c",
  "redwood": "#5b342e",
  "orangebrown": "#b16002",
  "rain": "#abbebf",
  "sunrise": "#f4bf77",
  "biscuit": "#feedca",
  "gingerbread": "#8c4a2f",
  "brightblue": "#0165fc",
  "brig": "#4fa1c0",
  "coco": "#d1bba1",
  "cookie": "#ffe2b7",
  "latte": "#c5a582",
  "cocoa": "#875f42",
  "sepia": "#704214",
  "tomato": "#ef4026",
  "hazel": "#a36b4b",
  "milk": "#fdfff5",
  "safetyorange": "#ff6600",
  "bark": "#5f5854",
  "bonewhite": "#f1e1b0",
  "darksalmon": "#c85a53",
  "brownish": "#9c6d57",
  "oxblood": "#800020",
  "purplered": "#990147",
  "dustyrose": "#b56f76",
  "purewhite": "#f8f8f2",
  "ashgrey": "#c1b5a9",
  "pastelred": "#ff6961",
  "steelblue": "#4682b4",
  "cerise": "#ad134e",
  "purplepink": "#c83cb9",
  "rouge": "#ab1239",
  "brightwhite": "#f6f2f1",
  "3amlatte": "#c0a98e",
  "palepink": "#efcddb",
  "mulberry": "#920a4e",
  "iris": "#5a4fcf",
  "cerulean": "#55aaee",
  "rosepink": "#ff66cc",
  "darkviolet": "#34013f",
  "coolgrey": "#8c93ad",
  "cinnabar": "#730113",
  "paleblue": "#d0fefe",
  "greige": "#b0a999",
  "grapefruit": "#fd5956",
  "redpurple": "#e40078",
  "fossil": "#867367",
  "blueblue": "#2242c7",
  "bluish": "#2976bb",
  "indianred": "#850e04",
  "flax": "#eedc82",
  "fireengine": "#fe0002",
  "rosewood": "#65000b",
  "ghostwhite": "#f8f8ff",
  "greyish": "#cfcac7",
  "lightbeige": "#e5deca",
  "alabaster": "#f3e7db",
  "iceblue": "#739bd0",
  "pinkish": "#d46a7e",
  "deeppurple": "#36013f",
  "creamy": "#efe8db",
  "pinky": "#fc86aa",
  "fuchsia": "#ed0dd9",
  "royalpurple": "#4b006e",
  "salt": "#efede6",
  "ecru": "#c2b280",
  "amaranth": "#e86ead",
  "vermilion": "#f4320c",
  "rubyred": "#9b111e",
  "rosegold": "#b76e79",
  "gainsboro": "#dcdcdc",
  "darkmaroon": "#3c0008",
  "orangepink": "#ff6f52",
  "stop": "#c33a36",
  "ultramarine": "#1805db",
  "seashell": "#fff5ee",
  "cloudy": "#d8d7d3",
  "burntred": "#9f2305",
  "concrete": "#d2d1cd",
  "pinkpurple": "#db4bda",
  "blackberry": "#43182f",
  "snowwhite": "#eeffee",
  "greybrown": "#7f7053",
  "frost": "#e1e4c5",
  "misty": "#cdd2d2",
  "cool": "#96b3b3",
  "emeraldgreen": "#046307",
  "ghost": "#c0bfc7",
  "pastelpurple": "#b39eb5",
  "dove": "#b3ada7",
  "whiteblue": "#cdd6db",
  "winered": "#7b0323",
  "palegrey": "#fdfdfe",
  "springgreen": "#00ff7c",
  "coconut": "#965a3e",
  "pewter": "#91a092",
  "blueviolet": "#4e32b2",
  "amethyst": "#9966cc",
  "pomegranate": "#b53d45",
  "reddishbrown": "#7f2b0a",
  "chalk": "#edeae5",
  "platinum": "#e5e4e2",
  "neonpurple": "#bc13fe",
  "cottoncandy": "#ffbcd9",
  "lipstickred": "#c0022f",
  "cranberry": "#9e003a",
  "brownishred": "#9e3623",
  "darkrose": "#b5485d",
  "brightpurple": "#be03fd",
  "greywhite": "#d7d5cb",
  "crimsonred": "#980001",
  "porcelain": "#dddcdb",
  "seablue": "#006994",
  "brownsugar": "#ab764e"
};

// Normalize a color name for hex lookup
function normalizeColorName(name: string): string {
  return name.toLowerCase().replace(/ /g, '');
}

// Get the hex code for a color name
export function getColordleColorHex(colorName: string): string {
  const normalized = normalizeColorName(colorName);
  return COLOR_HEX_MAP[normalized] || '#000000';
}

// Get the display name for a color (title case)
export function getColordleDisplayName(colorName: string): string {
  return colorName.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

// Calculate the day number for a given date
// Uses IST timezone (UTC+5:30) with rollover at 16:30 UTC
export function getColordleDayNumber(date: Date): number {
  // Colordle rolls over at 16:30 UTC (which is 10:00 PM IST)
  // After 16:30 UTC, the next day's puzzle is shown
  const utcMs = date.getTime();
  const rollover = new Date(Date.UTC(
    date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), 16, 30, 0
  ));
  
  let effectiveDate = new Date(utcMs);
  if (utcMs >= rollover.getTime()) {
    effectiveDate = new Date(utcMs + 86400000); // Move to next day
  }
  
  const startMs = COLORDLE_START_DATE.getTime();
  const daysSinceStart = Math.floor((effectiveDate.getTime() - startMs) / 86400000);
  return COLORDLE_DAY_OFFSET + daysSinceStart;
}

// Get the index into the color list for a given date
export function getColordleIndex(date: Date): number {
  const startMs = COLORDLE_START_DATE.getTime();
  const utcMs = date.getTime();
  
  // Apply rollover
  const rollover = new Date(Date.UTC(
    date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), 16, 30, 0
  ));
  
  let effectiveMs = utcMs;
  if (utcMs >= rollover.getTime()) {
    effectiveMs = utcMs + 86400000;
  }
  
  const daysSinceStart = Math.floor((effectiveMs - startMs) / 86400000);
  return ((daysSinceStart % COLORDLE_COLORS.length) + COLORDLE_COLORS.length) % COLORDLE_COLORS.length;
}

// Get the Colordle answer for a given date
export function getColordleAnswer(dateStr: string): {
  date: string;
  dayNumber: number;
  colorName: string;
  colorHex: string;
  formattedDate: string;
} {
  const date = new Date(dateStr + 'T12:00:00Z');
  const index = getColordleIndex(date);
  const colorName = COLORDLE_COLORS[index];
  const dayNumber = getColordleDayNumber(date);
  const hex = getColordleColorHex(colorName);
  const displayName = getColordleDisplayName(colorName);
  
  const formattedDate = date.toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC'
  });
  
  return {
    date: dateStr,
    dayNumber,
    colorName: displayName,
    colorHex: hex,
    formattedDate
  };
}

// Get today's date in IST
export function getTodayIST(): string {
  const now = new Date();
  // IST is UTC+5:30
  const istOffset = 5.5 * 60 * 60 * 1000;
  const istTime = new Date(now.getTime() + istOffset + now.getTimezoneOffset() * 60000);
  return istTime.toISOString().slice(0, 10);
}
